#!/usr/bin/env python3

from modules import *

class	Helper():
	def	__init__(self):
		if len(sys.argv):
			self.parsing = Parsing()
		else:
			self.setup = Setup()
if __name__ == "__main__":
	helper = Helper()
	# setup = Setup()
